language: python

python:
  - 2.7

install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install --upgrade pip
  - bin/pip install -r requirements.txt
  - bin/buildout -Nc travis.cfg

script:
  - bin/test
  - bin/coverage

after_success:
  - bin/coverage run bin/test
  - pip install coverage
  - python -m coverage.pickle2json
  - pip install coveralls
  - coveralls

notifications:
  email:
    - devs@imio.be
